### ISSUE TITLE
Unable to build on Fedora 19

### ISSUE THREAD

**Issue by nemequ** [mathieuchartier/mcm#1]
I would like to add a [Squash](http://quixdb.github.io/squash/) plugin for MCM (issue tracked at https://github.com/quixdb/squash/issues/27), but it seems to be Windows-only at the moment.

After changing the typedefs at Util.hpp:57-58 to use `int64_t` and `uint64_t` instead of `__int64` and `unsigned __int64` (since there is no __int64) and commenting out the `#include <Windows.h>` in Memory.cpp, I still get http://paste.fedoraproject.org/34196/13772378/ on Fedora 19 (with g++ 4.8.1).

**Comment by mathieuchartier** [comment]
Fixed
